### ISSUE TITLE
apiclient.discovery.build crashes during authentication

### ISSUE THREAD

**Issue by wsw70** [google/google-api-python-client#140]
The authentication flow as described in [the documentation](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) crashes on some platforms:

Sample code:
    import oauth2client.client
    import httplib2
    import platform
    import apiclient

```
print(platform.python_version())
print((oauth2client.__version__, httplib2.__version__, apiclient.__version__))

with open('galarmclock.p12', 'rb') as f:
    private_key = f.read()

credentials = oauth2client.client.SignedJwtAssertionCredentials(
    'mail-from-api-console@developer.gserviceaccount.com',
    private_key,
    'https://www.googleapis.com/auth/calendar.readonly',
    sub='a-sub@example.com'
)
http_auth = credentials.authorize(httplib2.Http())
service = apiclient.discovery.build('calendar', 'v3', http=http_auth)
print(service)
```

Output on a RPi with raspbian:

```
3.4.3+
('1.5.1', '0.9.2', '1.4.2')
Traceback (most recent call last):
  File "testauthgoogle.py", line 19, in <module>
    service = apiclient.discovery.build('calendar', 'v3', http=http_auth)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 196, in build
    cache)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 242, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 565, in new_request
    self._refresh(request_orig)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 835, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 862, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 1541, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 1670, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/_openssl_crypt.py", line 120, in from_string
    pkey = crypto.load_pkcs12(key, password).get_privatekey()
TypeError: must be str, not bytes
```

The same code on a Windows 8.1:

```
3.4.3
('1.5.1', '0.9.2', '1.4.2')
<googleapiclient.discovery.Resource object at 0x0380F530>
```

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the report and our apologies for the trouble.

Your code differs from the sample code on the page you linked in that the sample shows `with open("MyProject.p12") as f:` but your code contains `with open('galarmclock.p12', 'rb') as f:`. Could the change of file mode be the reason you're seeing a problem?

**Comment by pferate** [comment]
Opening the file with `'rb'` as opposed to `'r'` (default) seems like a likely suspect.

I seem to recall coming across a similar issue when working on oauth2client; which came down to the version of pyopenssl installed.  0.14 was a complete rewrite and fixed many of the python 3 problems from 0.13.

@wsw70, what versions of pyopenssl are installed on the 2 systems?

**Comment by pferate** [comment]
This looks very similar to the failures that Danny saw in google/oauth2client/issues/261.  We ended up dropping the separate tests for 0.13 and 0.14.

**Comment by JustinBeckwith** [comment]
Greetings!  This issue is getting a little old, and we're not sure if it's still a problem.  We're going to close it out for now.  If this is still giving you trouble... please do let us know!
