### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by philoniare** [google/google-api-python-client#167]
Hi, I am getting an ImportError: cannot import name 'urlencode'
Here's the whole Traceback 
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from apiclient.discovery import build
  File "C:\Program Files (x86)\Python35\lib\site-packages\apiclient-1.0.2-py3.5.egg\apiclient\__init__.py", line 1, in <module>
  File "C:\Program Files (x86)\Python35\lib\site-packages\apiclient-1.0.2-py3.5.egg\apiclient\base.py", line 4, in <module>
ImportError: cannot import name 'urlencode'
I have Python 3.5.1 installed and I am trying to run a tutorial script on official youtube API code sample for python: https://developers.google.com/youtube/v3/code_samples/python
The specific script is Search by keyword. Is this a apiclient issue with trying to import urlencode?

**Comment by nathanielmanistaatgoogle** [comment]
I think you want to contact the folks over at [the github.com/shazow/apiclient issue tracker](https://github.com/shazow/apiclient/issues).
