### ISSUE TITLE
Cannot call rmtree on a symbolic link

### ISSUE THREAD

**Issue by LittleLama** [google/google-api-python-client#171]
Hi !

I got this message when installing the package.
Could you help to find where I can fix it ?
Thank you very much.

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_set.py", line 725, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 752, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/utils/__init__.py", line 266, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 232, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 230, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```

**Comment by nathanielmanistaatgoogle** [comment]
@LittleLama: can you share with us the exact command that produced that output when you executed it? And on what platform (hardware, operating system including version, and so forth)? And what version of `pip`?

If you're curious about effective bug reporting [here's my favorite essay on the subject](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by LittleLama** [comment]
Hi Nathaniel and thank you for taking some time to answer my problem.

I read your essay, and will be as verbose as I can.
So here's the situation.
I'm trying to install google-api-python-client to make work a youtube-uploader made by tokland and found here : https://github.com/tokland/youtube-upload

I'm totally unfamiliar with python, and no so skilled with Linux, so let's get facts.

My server is : 
- Synology running DSM5.2-5565 (Xpenology version)
- Model 3615xs with i5-4570 and 16GB ram
- The system is bootstraped so I can run ipkg
- Python 2.7.9 is installed
- pip 8.0.2 from /usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg is installed

I'm running commands via root access, using BusyBox v1.16.1 built-in shell (ash).
So now when I follow the instructions here's what happens.

```
$ pip install --upgrade google-api-python-client
Collecting google-api-python-client
  Using cached google_api_python_client-1.4.2-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.6.1 in /lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from google-api-python-client)
Requirement already up-to-date: uritemplate>=0.6 in /lib/python2.7/site-packages (from google-api-python-client)
Collecting oauth2client>=1.4.6 (from google-api-python-client)
Collecting httplib2>=0.8 (from google-api-python-client)
Requirement already up-to-date: simplejson>=2.5.0 in /lib/python2.7/site-packages (from uritemplate>=0.6->google-api-python-client)
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.4.6->google-api-python-client)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client>=1.4.6->google-api-python-client)
  Using cached rsa-3.3-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client>=1.4.6->google-api-python-client)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Installing collected packages: pyasn1, pyasn1-modules, rsa, httplib2, oauth2client, google-api-python-client
  Found existing installation: pyasn1 0.1.7
    Uninstalling pyasn1-0.1.7:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_set.py", line 725, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 752, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/utils/__init__.py", line 266, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 232, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 230, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```

Hope this will help you ... and could help me too ^^
Thanks

**Comment by nathanielmanistaatgoogle** [comment]
Oh, it's not my essay, it's just an essay that I really esteem by someone else.

I'll leave this issue open a little while in case your problem recurs, but if the difficulty doesn't recur then I doubt the issue will be worth much investigation.

Glad to hear that you're making progress now.

**Comment by LittleLama** [comment]
Works like a charm. Thank you :) :+1:
