### ISSUE TITLE
Freeze when network outage/slow 

### ISSUE THREAD

**Issue by brendam** [google/google-api-python-client#235]
I've got what seems like a freeze, doesn't seem to time out and when I use ^C to interupt I get this stack trace:

```
^CTraceback (most recent call last):
  File "main.py", line 99, in <module>
    tsv_to_df_function)
  File "main.py", line 55, in tcat_to_gbq
    chunksize=1000)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/pandas/io/gbq.py", line 716, in to_gbq
    if not connector.verify_schema(dataset_id, table_id, table_schema):
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/pandas/io/gbq.py", line 483, in verify_schema
    tableId=table_id
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/googleapiclient/http.py", line 827, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/googleapiclient/http.py", line 154, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/oauth2client/client.py", line 631, in new_request
    redirections, connection_type)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/site-packages/httplib2/__init__.py", line 1046, in _conn_request
    content = response.read()
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/http/client.py", line 440, in read
    return self._readall_chunked()
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/http/client.py", line 543, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/http/client.py", line 526, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/http/client.py", line 486, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/home/ubuntu/miniconda3/envs/tcat-to-bigquery/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
```

**Comment by jonparrott** [comment]
Thanks for reporting.

We're likely not setting any sort of socket read timeout on connecting. I'm not even sure httplib2 will let you set that. I'll try to investigate in a few weeks when I return from vacation, but if you can find a fix before then I'm happy to review.

**Comment by brendam** [comment]
I've had a look and httplib2 does support timeout:

> class Http([cache=None], [timeout=None], [proxy_info=None])
> The class that represents a client HTTP interface. The cache parameter is either the name of a directory to be used as a flat file cache, or it must an object that implements the required caching interface. The timeout parameter is the socket level timeout. The proxy_info is an instance of ProxyInfo and is supplied if a proxy is to be used. Note that the Socksipy module must be installed for proxy support to work.

But I can't work out how to use this in the google-api-python-client http.py code.

**Comment by jonparrott** [comment]
> But I can't work out how to use this in the google-api-python-client http.py code. 

We may need to expose that somehow. If you have any ideas, I'm happy to review a PR.

**Comment by TimotheeJeannin** [comment]
Any updates on this issue ?

**Comment by TheGU** [comment]
I think it already fix in #320. 
May be this code
https://github.com/google/google-api-python-client/commit/2243529e68a76f5419b2ba62aae2efef5eba2d98#diff-84a6c030bfdfe3ce2eac14a3369e6114

**Comment by mcdonc** [comment]
#320 does indeed solve this, and there are docs checked in to the package which describe the use of socket.setdefaulttimeout() to override the default timeout.  However, those docs are not the most current published version, AFAICT.  https://google.github.io/google-api-python-client/docs/epy/googleapiclient.http-module.html does not match what's checked in to the repo.

**Comment by mcdonc** [comment]
Awaiting merge of https://github.com/google/google-api-python-client/pull/533
