### ISSUE TITLE
Where should I give packageName to discovery.build when using androidpublisher API?

### ISSUE THREAD

**Issue by wonderchang** [google/google-api-python-client#245]
I am curious about whether this part (as the title) have been implemented or not, because I haven't seen any corresponding `packageName` parameter in `discovery.py`. My problem is, for example, I want to get my app's reviews on Google Play, like,

```
http = credentials.authorize(httplib2.Http())
service = build('androidpublisher', 'v2', http=http)
service.reviews().list().execute()
```

Obviously, the request is lack of given packageName, the error happened,

```
Traceback (most recent call last):
File "get_review.py", line 44, in <module>
File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 691, in method
raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "packageName"
```

**Comment by jonparrott** [comment]
I think you should be doing

```
service.reviews(packageName='your-package-name').list().execute()
```

I'm not sure, as I'm unfamiliar with the androidpublisher API.

**Comment by wonderchang** [comment]
I've tried that, but it does not work. The error is

```
Traceback (most recent call last):
  File "get_review.py", line 59, in <module>
    service = build('androidpublisher', 'v2', http=http)
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
TypeError: build() takes at least 3 arguments (3 given)
```

**Comment by jonparrott** [comment]
That's odd. Can you share you full code? I think I'm missing some context here.

**Comment by wonderchang** [comment]
```
from oauth2client.client import flow_from_clientsecrets, save_to_well_known_file, OAuth2WebServerFlow
from oauth2client.file import Storage
from apiclient.discovery import build
from apiclient.http import HttpRequest
from datetime import datetime
import httplib2, json, time

PACKAGE_NAME = 'your package name'
CLIENT_ID = 'your client ID'
CLIENT_SECRET = 'your client secret'
REDIRECT_URI = 'your redirect uri'

def load_credentials():
    return Storage('credentials.json').get()

def access_token_expired(credentials):
    return datetime.utcnow() > credentials.token_expiry

def refresh_credentials(credentials):
    http = credentials.authorize(httplib2.Http())
    credentials.refresh(http)
    storage = Storage('credentials.json').put(credentials)
    return credentials

def get_credentials():
    flow = OAuth2WebServerFlow(client_id=CLIENT_ID,
                               client_secret=CLIENT_SECRET,
                               scope='https://www.googleapis.com/auth/androidpublisher',
                               redirect_uri=REDIRECT_URI)

    auth_uri = flow.step1_get_authorize_url()
    print "Please navigate your browser to the following URL:\n%s\n" % auth_uri

    code = raw_input('Enter the authorization code: ')
    credentials = flow.step2_exchange(code)
    storage = Storage('credentials.json')
    storage.put(credentials)

    return credentials


if __name__ == '__main__':

    credentials = load_credentials()

    if not credentials:
        credentials = get_credentials()
    elif access_token_expired(credentials):
        credentials = refresh_credentials(credentials)

    http = credentials.authorize(httplib2.Http())
    service = build('androidpublisher', 'v2', http=http)
    service.reviews(packageName=PACKAGE_NAME).list().execute()

```

**Comment by jonparrott** [comment]
Hmm, when I execute:

```
from googleapiclient.discovery import build
build('androidpublisher', 'v2')
```

I do not get an error. Can you confirm which version of the library you're using?

**Comment by prsolucoes** [comment]
Traceback (most recent call last):
  File "test.py", line 117, in <module>
    service.reviews(packageName=PACKAGE_NAME).list().execute()
TypeError: methodResource() got an unexpected keyword argument 'packageName'

Can anyone help me?

**Comment by mcdonc** [comment]
The comment from @badnoodle describes the correct way to call this API.
