### ISSUE TITLE
Python Api not working for Picasa/Google Photo

### ISSUE THREAD

**Issue by NotaLabs** [google/google-api-python-client#246]
Hello,
i tried to use the ypthon api with picasa/google photo. I got the authentification process right, but then i get an error when i try to build the api object for picasa.

```
import httplib2
from oauth2client import client
from googleapiclient.discovery import build

flow = client.flow_from_clientsecrets(
    'client_secret.json',
    scope='https://picasaweb.google.com/data/',
    redirect_uri='http://localhost')

auth_uri = flow.step1_get_authorize_url()
print(auth_uri)

auth_code = input("Please enter the auth code ")

credentials = flow.step2_exchange(auth_code)
http_auth = credentials.authorize(httplib2.Http())

picasa = build('picasa',http_auth)

```

I get the following error:

```
C:\Users\Tim\AppData\Local\Programs\Python\Python35-32\python.exe C:/Users/Tim/PycharmProjects/copy+/googleconnect.py
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=146286492829-5nl303un65ng7ublcmir31jng2voh8br.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost&scope=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2F&access_type=offline
Please enter the auth code 4/zSkse9IsnMnOxeeRB9wis3u_QIdLkBlmUCMZrCj9Bac#
Traceback (most recent call last):
  File "C:/Users/Tim/PycharmProjects/copy+/googleconnect.py", line 18, in <module>
    picasa = build('picasa',http_auth)
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python35-32\lib\site-packages\oauth2client\util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python35-32\lib\site-packages\googleapiclient\discovery.py", line 218, in build
    "name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: picasa  version: <httplib2.Http object at 0x00E87EF0>

Process finished with exit code 1

```

Am i using the wrong name to build the api-object or is picasa not supported ?

**Comment by jonparrott** [comment]
It appears not. If the API is not listed [here](https://developers.google.com/api-client-library/python/apis/), then it's not supported/doesn't exist.

**Comment by jonparrott** [comment]
I seems like there's a Picasa API based on the (very old) gdata APIs [here](https://developers.google.com/picasa-web/docs/1.0/developers_guide_python). This client library does not support those APIs.

**Comment by k-funk** [comment]
:(
gdata doesn't support python3: https://github.com/google/gdata-python-client/issues/29 and this library doesn't support any api to picasa/google photos.
Is there any python3 library to get photos, or one in the works?
