### ISSUE TITLE
earthengine authenticate

### ISSUE THREAD

**Issue by dhananjaymehta** [google/google-api-python-client#251]
Error Logs: 
Traceback (most recent call last):
  File "~/anaconda/bin/earthengine", line 11, in <module>
    sys.exit(main())
  File "~/anaconda/lib/python3.5/site-packages/ee/cli/eecli.py", line 63, in main
    dispatcher.run(args, config)
  File "~/anaconda/lib/python3.5/site-packages/ee/cli/commands.py", line 226, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "~/anaconda/lib/python3.5/site-packages/ee/cli/commands.py", line 252, in run
    token = ee.oauth.request_token(auth_code)
  File "~/anaconda/lib/python3.5/site-packages/ee/oauth.py", line 56, in request_token
    urllib.parse.urlencode(request_args)).read()
  File "~/anaconda/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "~/anaconda/lib/python3.5/urllib/request.py", line 464, in open
    req = meth(req)
  File "~/anaconda/lib/python3.5/urllib/request.py", line 1183, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

How I resolved it : I had to explicitly encode data parameter(urllib.parse.urlencode(request_args) ) for urllib.request.urlopen() from str to bytes and then had to again decode response variable from byte to str for refresh_token.

**Comment by jonparrott** [comment]
Can I see the code you're using here?

**Comment by dhananjaymehta** [comment]
I made below changes in my code in oauth.py:
try: #Line 54
parm=str.encode(urllib.parse.urlencode(request_args))
response = urllib.request.urlopen('https://accounts.google.com/o/oauth2/token',parm).read()
response=bytes.decode(response)
refresh_token = json.loads(response)['refresh_token']

@jonparrott Does this help? Please let me know if you need any other input.

**Comment by jonparrott** [comment]
Oh, okay, I understand. This is not the API client you're using. You should report this issue over at https://github.com/google/earthengine-api.
