### ISSUE TITLE
Six Package: Compatibility Bug

### ISSUE THREAD

**Issue by baptistapedro** [google/google-api-python-client#264]
As soon as I tried to work import urlparse I went through a couple of issues with the package dependency version.

Traceback (most recent call last):
File "collect.py", line 6, in 
from the_finder import results
File "/Users/shaikhpiedro/proj/the_finder.py", line 1, in 
from googleapiclient.discovery import build
File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 33, in 
from six.moves.urllib.parse import urlencode, urlparse, urljoin, \
ImportError: No module named urllib.parse

I checked my six.version. which was '1.10.0' and by uninstalling it and pip install six==1.6.1 solved the issue
on the docs says 'six>=1.6.1,<2' and it can't support 1.10.0 so it's clearly a bug,

just have to change the install_requirements on setup.py

**Comment by jonparrott** [comment]
Thanks for reporting this, I'll try to address it in the next release.

**Comment by jonparrott** [comment]
@baptistapedro I couldn't reproduce this with six 1.10.0.

**Comment by jonparrott** [comment]
@baptistapedro I'm closing this issue due to inactivity. If you're still experiencing this, please let us know and we'll re-open.
