### ISSUE TITLE
'utf8' codec can't decode byte 0x8b in position 14: invalid start byte

### ISSUE THREAD

**Issue by JosephLing** [google/google-api-python-client#277]
I get this error sometimes when requesting resources using `.get()` in this case it was with requesting
 `repsonse = compute.images().get(project=project, image=iamgeName).execute()`
 has anyone else got this before? is a problem with data stored in my instances or images? or is it with requesting the data?

`File "venv/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper return wrapped(*args, **kwargs)`
`File "venv/lib/python2.7/site-packages/googleapiclient/http.py", line 839, in execute return self.postproc(resp, content)`
`File "venv/lib/python2.7/site-packages/googleapiclient/model.py", line 209, in response return self.deserialize(content)` 
`File "venv/lib/python2.7/site-packages/googleapiclient/model.py", line 264, in deserialize content = content.decode('utf-8') `

This is the version I am using on python2.7: 
google-api-python-client==1.5.3
httplib2==0.9.2
oauth2client==2

So I was able to replicate it by surprise while testing SSL errors in threading it turns out the first thread gets a JSON error while the second gets a utf-8 error.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/python2.7/lib/python2.7/threading.py", line 530, in __bootstrap_inner
    self.run()
  File "/opt/python2.7/lib/python2.7/threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "SSLerrorTesting.py", line 28, in getImages
    r = compute.images().list(project=project).execute()
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/googleapiclient/http.py", line 839, in execute
    return self.postproc(resp, content)
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/googleapiclient/model.py", line 209, in response
    return self.deserialize(content)
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/googleapiclient/model.py", line 264, in deserialize
    content = content.decode('utf-8')
  File "/sv/venv/svLoadCloudController/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 23: invalid start byte

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python2.7/lib/python2.7/threading.py", line 530, in __bootstrap_inner
    self.run()
  File "/opt/python2.7/lib/python2.7/threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "SSLerrorTesting.py", line 21, in getInstances
    r = compute.instances().list(project=project, zone=zone).execute()
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/googleapiclient/http.py", line 839, in execute
    return self.postproc(resp, content)
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/googleapiclient/model.py", line 209, in response
    return self.deserialize(content)
  File "/sv/venv/svLoadCloudController/lib/python2.7/site-packages/googleapiclient/model.py", line 267, in deserialize
    body = json.loads(content)
  File "/opt/python2.7/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/opt/python2.7/lib/python2.7/json/decoder.py", line 360, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python2.7/lib/python2.7/json/decoder.py", line 378, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jonparrott** [comment]
@JosephLing can you reproduce this consistently?

**Comment by JosephLing** [comment]
Yes I can reproduce it consistently but to do so I am randomly delaying the request threads. The script I used to test it is at work so can show you the code tomorrow when I am at work.

**Comment by jonparrott** [comment]
Thanks, it would also be helpful if you can modify `googleapiclient/model.py` at line 264 to print the raw response.

**Comment by JosephLing** [comment]
```
debugging
00000001

00000001
�
00000001

00000001

00000001

00000001

00000001

00000001

00000001

00000001

00000001
�
00000001
V
00000001

00000001
n
00322
1}�+V����KX�*5�"5$�<TQd����k�l/$����/K �Z5�Bx�3g����p�a��w\̳�P��0����H�h	t����q�S*�� X�V~�yJ�D��n`��(���d 1YYd��D�T���/�@���҇���*�,3��?GQ�I�g�q����R��S����8>�z�Vw�v7�v�
                                                                                                                                                                                     @�p6%�N��ܸ7���
                                                                                                                                                                                                  {^OøE�V����
                                                                                                                                                                                                               ��0����V����X��5v{�Pjp��w���
�3.VH��J����b1d�x<�/���>���42�G^F���.N�;�1
*�樠j������oB�V�˾u�}UG�
n����kt4�r�4c             �(��V�fm��e��C�u��	gs��-�4���ھQ�1���
              Qg׬*�m?�t�Þ�
7�Iio�����&��8�%�{��,K�a���1ˎ%��mau0��,%Z㐜j�M����x2�L�
�0^(~
��$l��oKL`F�0�ERML�2�޽��M��N��mr2�{\g�P����.���lu��v��Ş� Lg�S�r�
                                                                        Z>
                                                                           �8j����{6�
P͟�S���6ղ���O{�9�
                 �.z9Ej�E��5��%�S��KA�՚ξr�.����o��v1<m樔a�_^<6Ϯx�R�7 �O��B�����yqU�EG6ou��G�X�$-��;t�xn��x�
                                                                                                                 	
0


debugging

```
Here is the change I did to model.py
```

  def deserialize(self, content):
    print("debugging")
    print(content)
    try:
        content = content.decode('utf-8')
    except AttributeError:
        pass
    body = json.loads(content)
    if self._data_wrapper and isinstance(body, dict) and 'data' in body:
      body = body['data']
    return body
```

**Comment by jonparrott** [comment]
It seems this request is encoded. You might need to go up in the stack and print the headers, perhaps `googleapiclient/http.py`, line 839?

**Comment by JosephLing** [comment]
This is output self.hearders from http
```
get images 2
debugging headers
{'content-length': debugging headers
'0', 'accept-encoding'{'content-length': '0', 'accept-encoding': ': g'gzizipp,, d eflate'd, e'flaacctepe't, 'a'ccept': 'ap: plication'ap/plicatijsoon/njson'', , 'u'ser-agenut': ser-ag'goeogle-ant'pi-pyt: h'gooon-cglient/1.5le-.3api -python(-gzip)c'}lient/1.5.3 (gzip)'
}
-------
-------
debugging
debugging
TExpires:
HTP/1.1 200 OK
 Fri, 09 Sep 2016 16:27:52 GMT
Date: Fri, 09 Sep 2016 16:27:52 GMT
Cache-Control: private, max-age=0, must-revalidate, no-transform
ETag: "AX7Y5bwcG6-xdsRgDlr5Qutm4QI/7mk0bMpemT4q--uqE84BoailXG4"
Vary: Origin
Vary: X-Origin
Content-Type: application/json; charset=UTF-8
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="36,35,34,33,32"
Transfer-Encoding: chunked

00000001

00000001
�
00000001

001

442
��Ko�F����z��y�c��)�9���ȁ�h��$                                                                                     g��Ԗ�F��~1}��#Oێ�&
U�ul��e��o��h�����l�r�����Vf�f��`e>�u\��2�]�Ŷi'X_]-�U9A�ِuv�tV6ŦZG3�Ǯ������ޭ������}y��ۦ+�����v���x_ݔ�T���tnb=zF��!e�H;                    ��
                            qr�F�M�e:&�&���"o˯��S���D���(��Z.��\5��ӣ�#��m�L�E���1��t_�����vc; �铜��O���
�G��^8�����B⑞ƙ�,��@�ʃ~���L�pf�.%`������'Cq�<��a/ț`���2��m�A<3�;��r�<;�8�>�eѽ&8�p^<w�          
                                                                                                 �Y@w3	�3+�$����3���$Ƴ�x
                                                                                                                           �,������Z�I�X rf<GN�
���X r-xvۄ�
              �Y��1��#vt�<��6���j&^<w�
                                          *Έ�ŠR�
                                                  ��De�0���HsP����������tUꥺCe��鍎��<��Vf4�v����58k>(	ĳ�es
�*�♦@Qo %�O��{��Q��x��Ӭ��yS                                                                                ��Xz��ga�.�"�k:��,�8�3�~�F�5�|C�B�?��|>�ȳ�ǉώ�.Ϟ4d�l��E�Ό���`�!茡�����ͻ~<�LF6�!Q	>�g�ě�����y9�
���y��9�N�t�TO�WU��f�߶T���Xg�ȩ�E�?'��;Se�mF>���{����t=^V0�� _�k�^��1���ڀ&�|>���
                                                                                    ���aW�M���~'��>3�H����/} .Y	���;z}��
                                                                                                                                �~`�:	<���;@�ʗ����{�D�/F�.>]�	ww��c"
0


```

**Comment by jonparrott** [comment]
The content appears to be gzipped but for some reason httplib2 isn't decoding it or is decoding it incorrectly.

Hmm. Can you maybe try manually unzipping the content? Maybe something like:

```python
import gzip
import StringIO
print(gzip.GzipFile(fileobj=StringIO.StringIO(content)).read())
```

(FYI, I can't reproduce this myself, so I'm asking you to do all this so I can figure out what's going on)

**Comment by JosephLing** [comment]
Sorry, for not getting back sooner. I have left my summer so don't have access to the server to server key to authorise connect to google cloud api to test it. Here is the code that I used to test from what I can remember. 

```
import threading
import time
import threading
import random
from GoogleAPI.AuthoriseAPI import Authorise
# Authroise: grabs the server to server key named 'main' and returns the build(...)
compute = Authorise("main") 
project = ""
zone = ""


def getImages():
    for i in range(10):
        time.sleep(random.random())
        print("getImages")
        compute.images().list(project=project)

def getInstance():
    for i in range(10):
        time.sleep(random.random())
        print("getInstance")
        compute.instances().get(project=project, zone=zone, instance="instance-1")


if __name__ == "__main__":
    a = threading.Thread(target=getImages)
    b = threading.Thread(target=getInstance)
    
    a.start()
    b.start()

```

**Comment by jonparrott** [comment]
Ah I should've picked up on this sooner.

httplib2 isn't thread safe, so by using the same client across multiple threads you're running into corruption of the underlying socket.

I'd recommend either building a new client in each thread or using something like httplib2shim.
