### ISSUE TITLE
httplib2.sslhandshakerror

### ISSUE THREAD

**Issue by SJonny95** [google/google-api-python-client#323]
have tried everything I can find to get this to work...

I'm working on a project for my school with Google Vision Api on Raspberry Pi. The python code is:

import argparse
import base64
import picamera

from googleapiclient import discovery
from oauth2client.client import GoogleCredentials
from googleapiclient.discovery import build

def main():

    """Run a label request on a single image"""

    credentials = GoogleCredentials.get_application_default()
	

    service = build('vision', 'v1', credentials=credentials)

    with open('coca.jpeg', 'rb') as image:
        image_content = base64.b64encode(image.read())
        service_request = service.images().annotate(body={
            'requests': [{
                'image': {
                    'content': image_content.decode('UTF-8')
                },
                'features': [{
                    'type': 'LOGO_DETECTION',
                    'maxResults': 1
                }]
            }]
        })
        response = service_request.execute()
	print response
	print " \n\n"

        try:
             label = response['responses'][0]['logoAnnotations'][0]['description']
        except:
             label = "No response."
        print label
if __name__ == '__main__':
    main()

and the problem is:

root@raspberrypi:/home/pi# python camera-vision-logo.py 
Traceback (most recent call last):
  File "camera-vision-logo.py", line 56, in <module>
    main()
  File "camera-vision-logo.py", line 27, in main
    service = build('vision', 'v1', credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 222, in build
    cache)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 269, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
root@raspberrypi:/home/pi# 

HOW CAN I SOLVE THIS PROBLEM??

Thanks so much for the answers!

**Comment by jonparrott** [comment]
This error means that httplib2 is unable to verify the certificate for the API you're trying to talk to.

Make sure your OS has an up-to-date version of OpenSSL, or potentially disable certificate verification (highly discouraged).
