### ISSUE TITLE
search_analytics_api_sample.py fail to execute

### ISSUE THREAD

**Issue by andrewbrinck** [google/google-api-python-client#326]
Hi,

Having trouble getting sample file to execute. I have installed all packages for GSC API. I have created a client_secrets.json and stored it with the search_analytics_api_sample.py file. When I run the command line for $python search_analytics_api_sample.py 'https://www.myurl.com/' '2016-12-01' '2016-12-30' (valid date ranges) I get the attached log.
[pyLogGSC.txt](https://github.com/google/google-api-python-client/files/699561/pyLogGSC.txt)

**Comment by andrewbrinck** [comment]
<<LOG START>>

`python : Traceback (most recent call last):
At line:1 char:1
+ python search_analytics_api_sample.py 'https://www.myurl.com/' '2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "search_analytics_api_sample.py", line 146, in <module>
    main(sys.argv)
  File "search_analytics_api_sample.py", line 22, in main
    scope='https://www.googleapis.com/auth/webmasters.readonly')
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\site-packages\googleapiclient\sample_tools.py", line 81, in init
    message=tools.message_if_missing(client_secrets))
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\site-packages\oauth2client\util.py", line 135, in 
positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\site-packages\oauth2client\client.py", line 2195, in 
flow_from_clientsecrets
    cache=cache)
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\site-packages\oauth2client\clientsecrets.py", line 166, in 
loadfile
    return _loadfile(filename)
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\site-packages\oauth2client\clientsecrets.py", line 123, in 
_loadfile
    obj = json.load(fp)
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

PS C:\Users\myUserId\AppData\Local\Continuum\Miniconda3\Lib\site-packages\oauth2client> python
python : Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
At line:1 char:1
+ python
+ ~~~~~~
    + CategoryInfo          : NotSpecified: (Python 3.5.2 |C...MD64)] on win32:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Type "help", "copyright", "credits" or "license" for more information.
>>> 
`

**Comment by lukesneeringer** [comment]
Hi @andrewbrinck 
Are you still hitting this?

Unfortunately, it has been ages (sorry about that), and so I am going to close this, but if you are still hitting it, please feel free to re-open it, and we will summon large numbers of Shakespearean monkeys to investigate.
