### ISSUE TITLE
v1.6.1, Ubuntu 14.04, Python 2.7.6: Cannot import names under googleapiclient

### ISSUE THREAD

**Issue by crunchex** [google/google-api-python-client#333]
Hi, I've installed the google-api-python-client 1.6.1 on my Ubuntu 16.04 system (Python 2.7.12) with the following dependencies:

uritemplate == 3.0.0
six == 1.10.0
oauth2client == 4.0.0
httplib2 == 0.9.2

and everything works great. However, when I replicate this setup on Ubuntu 14.04 (Python 2.7.6), I can't seem to import any names under the top level module:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import googleapiclient
\>\>\> from googleapiclient import discovery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name discovery
\>\>\> from googleapiclient import errors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name errors
\>\>\> from googleapiclient import channel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name channel
\>\>\> 

I have checked that google-api-python-client and its dependencies are indeed in /usr/local/lib/python2.7/dist-packages with the same versions and permissions. But the traceback is so short that I don't have anything to go off of (like investigating a circular import or something). So I'm thinking it must be a bug or a problem when using an older Python. Any ideas?

**Comment by crunchex** [comment]
Looks like Github clobbered my interpreter output. Hopefully you can get the idea.

**Comment by jonparrott** [comment]
@crunchex I'd highly recommend using virtualenv in any case.

But out of curiousity, could you do:

```
import googleapiclient

print(googleapiclient.__path__)
```

**Comment by crunchex** [comment]
@jonparrott I'll have to revisit how virtualenv works.

Here's the output:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import googleapiclient
>>> print(googleapiclient.__path__)
['/usr/local/lib/python2.7/dist-packages/googleapiclient']
>>>

**Comment by lukesneeringer** [comment]
Is this still a problem? (Closing for inactivity; feel free to re-open.)

**Comment by crunchex** [comment]
@lukesneeringer this is still a problem as I am back on the project that requires this library.

So again comparing my two systems with different versions of Ubuntu, on 16.04:

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import googleapiclient

In [2]: print googleapiclient
<module 'googleapiclient' from '/usr/local/lib/python2.7/dist-packages/googleapiclient/__init__.pyc'>

And on 14.04:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import googleapiclient

In [2]: print googleapiclient
<module 'googleapiclient' from '/usr/local/lib/python2.7/dist-packages/googleapiclient'>

So in the latter case, it looks like it's just not picking up the generated .pyc and I'm not sure why that is, as I was of the understanding that these are generated at the time of import.
