### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DEFAULT_MAX_REDIRECTS'

### ISSUE THREAD

**Issue by assafelovic** [google/google-api-python-client#343]
I've followed the basic Python Quickstart guide for using this api: https://developers.google.com/google-apps/calendar/quickstart/python

Everything went smoothly until running quickstart.py where I get this error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 42, in <module>
    import calendar
  File "calendar.py", line 5, in <module>
    from apiclient import discovery
  File "/Library/Python/2.7/site-packages/apiclient/__init__.py", line 19, in <module>
    from googleapiclient import discovery
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 56, in <module>
    from googleapiclient import _auth
  File "/Library/Python/2.7/site-packages/googleapiclient/_auth.py", line 29, in <module>
    import oauth2client.client
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 39, in <module>
    from oauth2client import transport
  File "/Library/Python/2.7/site-packages/oauth2client/transport.py", line 255, in <module>
    redirections=httplib2.DEFAULT_MAX_REDIRECTS,
AttributeError: 'module' object has no attribute 'DEFAULT_MAX_REDIRECTS'
```

I've tried reinstalling httplib2, upgrading and etc. Nothing works. Would appreciate any help thanks!

**Comment by jonparrott** [comment]
@assafelovic can you give me the output of `pip freeze`?

**Comment by jonparrott** [comment]
@assafelovic additionally the output of `python -c "import httplib2; print(httplib2.DEFAULT_MAX_REDIRECTS)"`

**Comment by jmcardon** [comment]
+1. Having the exact same issue

**Comment by lukesneeringer** [comment]
Closing for inactivity. If you are experiencing this problem, please give us a `pip freeze`. :-)

**Comment by jcschneider79** [comment]
Can this get re-opened?  I am getting the same error. Here's my pip freeze:

`(google_api) joe@Lanfear:google_admin 🏈  pip freeze
google-api-python-client==1.6.2
httplib2==0.10.3
oauth2client==4.0.0
pyasn1==0.2.3
pyasn1-modules==0.0.8
rsa==3.4.2
six==1.10.0
uritemplate==3.0.0
(google_api) joe@Lanfear:google_admin 🏈

**Comment by Lunran** [comment]
I got the same error and investigated on the problem.  
In my case, it was caused by a file named ''calendar.py" in the same directory.  
It's said you should avoid using general names that can be already used for standard python library.

**Comment by mistergoodson** [comment]
I'm getting this error. Output of `pip freeze`:

```APScheduler==3.3.1
astroid==1.5.3
backports.functools-lru-cache==1.4
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
configparser==3.5.0
enum34==1.1.6
Flask==0.12.2
Flask-Mandrill==0.3
Flask-SQLAlchemy==2.2
funcsigs==1.0.2
futures==3.1.1
google-api-python-client==1.6.2
httplib2==0.10.3
idna==2.6
isort==4.2.15
itsdangerous==0.24
Jinja2==2.9.6
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
oauth2client==4.1.2
psycopg2==2.7.3
pyasn1==0.3.2
pyasn1-modules==0.0.11
pylint==1.7.2
pytz==2017.2
requests==2.18.4
rsa==3.4.2
singledispatch==3.4.0.3
six==1.10.0
SQLAlchemy==1.1.13
tzlocal==1.4
uritemplate==3.0.0
urllib3==1.22
Werkzeug==0.12.2
wrapt==1.10.11
```

Thought it was my file being called `calendar.py` (as @Lunran suggested) but the issue still persists.

**Comment by dogwood008** [comment]
Hi there, I faced the same problem on Python 3.6.1, but it resolved when changed into Python 2.7. I'm happy if this helps you.

**Comment by santoshkumar241** [comment]
@dogwood008 Thanks a lot, it worked

**Comment by abhyudayasrinet** [comment]
[this](https://stackoverflow.com/a/50213172/1783688) can he helpful for anyone facing this issue
