### ISSUE TITLE
Can import google lib

### ISSUE THREAD

**Issue by cisarpavel** [google/google-api-python-client#345]
google-api-python-client==1.6.1
oauth2client==4.0.0

Usage based on google python api examples.
Ends with oauth closed issue ImportError: No module named locked_file https://github.com/google/oauth2client/issues/414

```
Traceback (most recent call last):
  File "/home/pavel/projects/venvs/exapro_3992/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pavel/projects/venvs/exapro_3992/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pavel/projects/venvs/exapro_3992/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pavel/projects/venvs/exapro_3992/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pavel/projects/venvs/exapro_3992/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
```

**Comment by jonparrott** [comment]
@cisarpavel this should be a warning, not an application-stopping exception. What does your calling code look like?

**Comment by cisarpavel** [comment]
Yeah, sorry, my bug. It's just warning. But I must say, that such chain of exceptions can be confusing in debug log.

**Comment by jonasman** [comment]
and how do we fix the warning?

**Comment by Chronial** [comment]
A workaround for this was posted here: https://github.com/google/google-api-python-client/issues/325#issuecomment-274349841
