### ISSUE TITLE
DCM report scheduled in GUI and downloading from Google App Engine - read only error

### ISSUE THREAD

**Issue by chaitu1124** [google/google-api-python-client#409]
Hi All,

I have scheduled the report in GUI and trying to pull it from Python API and want to store the file in google cloud storage and running these python scripts in google cloud app engine. 

I tried  to modify the code to run in google app engine. 

I modified the code as following (setup function code in dfareporting_utils.py script)

  CSF=os.path.join(os.path.dirname(__file__),
                                'dfareporting.dat')
  storage = oauthFile.Storage(CSF)
  print storage
  credentials = storage.get()

storage.get() is trying to create a file. In App engine we can’t create a file so is there any way to get credentials. 

Error Message:

Entering Appsetitngs
C:\Chaitu\Projects\DCM\dcmcontrollers\client_secrets.json
<oauth2client.client.OAuth2WebServerFlow object at 0x04D84E70>
<oauth2client.file.Storage object at 0x04D84C50>
WARNING  2017-07-03 13:39:08,325 urlfetch_stub.py:550] Stripped prohibited headers from URLFetch request: ['content-length']
##########################################
<oauth2client.client.OAuth2Credentials object at 0x04DA4FF0>
INFO     2017-07-03 17:39:08,315 discovery.py:822] URL being requested: GET https://www.googleapis.com/dfareporting/v2.7/userprofiles/4007638/reports/94841874/files?alt=json
INFO     2017-07-03 17:39:08,549 client.py:641] Refreshing due to a 401 (attempt 1/2)
INFO     2017-07-03 17:39:08,551 client.py:903] Refreshing access_token
ERROR    2017-07-03 17:39:08,782 webapp2.py:1528] [Errno 30] Read-only file system: 'C:\\Chaitu\\Projects\\DCM\\dcmcontrollers\\dfareporting.dat'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "C:\Chaitu\Projects\DCM\dcmcontrollers\dcmreports.py", line 20, in get
    response = request.execute()
  File "lib\oauth2client\util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "lib\googleapiclient\http.py", line 827, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "lib\googleapiclient\http.py", line 154, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "lib\oauth2client\client.py", line 642, in new_request
    self._refresh(request_orig)
  File "lib\oauth2client\client.py", line 885, in _refresh
    self._do_refresh_request(http_request)
  File "lib\oauth2client\client.py", line 925, in _do_refresh_request
    self.store.locked_put(self)
  File "lib\oauth2client\file.py", line 97, in locked_put
    f = open(self._filename, 'w')
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\python\stubs.py", line 247, in __init__
    raise IOError(errno.EROFS, 'Read-only file system', filename)
IOError: [Errno 30] Read-only file system: 'C:\\Chaitu\\Projects\\DCM\\dcmcontrollers\\dfareporting.dat'
ERROR    2017-07-03 17:39:08,789 wsgi.py:279]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.3\webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "C:\Chaitu\Projects\DCM\dcmcontrollers\dcmreports.py", line 20, in get
    response = request.execute()
  File "lib\oauth2client\util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "lib\googleapiclient\http.py", line 827, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "lib\googleapiclient\http.py", line 154, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "lib\oauth2client\client.py", line 642, in new_request
    self._refresh(request_orig)
  File "lib\oauth2client\client.py", line 885, in _refresh
    self._do_refresh_request(http_request)
  File "lib\oauth2client\client.py", line 925, in _do_refresh_request
    self.store.locked_put(self)
  File "lib\oauth2client\file.py", line 97, in locked_put
    f = open(self._filename, 'w')
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\python\stubs.py", line 247, in __init__
    raise IOError(errno.EROFS, 'Read-only file system', filename)

Thanks,

**Comment by mcdonc** [comment]
This issue was moved to google/oauth2client#739

**Comment by mcdonc** [comment]
I moved this issue to the oauth2client issue tracker, as it's actually an issue with this library, and not google-api-python-client itself.
