### ISSUE TITLE
Cannot Import Google Lib using buildout

### ISSUE THREAD

**Issue by XuryaX** [google/google-api-python-client#448]
I read the quickstart tutorial here for google spreadsheets

    https://developers.google.com/sheets/api/quickstart/python

I am reading a private google spreadsheet, when I run this script in virtualenv with python3.4, it runs good without any errors or exceptions.
But when I integrate this on my app, I get the following errors.
I am using buildout to install the google api python client along with other dependencies. The library versions in both are the same.

```
    WARNING googleapiclient.discovery_cache:autodetect file_cache is unavailable when using oauth2client >= 4.0.0
    Traceback (most recent call last):
      File "/home/shaurya/repos/api_test/eggs/google_api_python_client-1.6.4-py3.4.egg/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
        from google.appengine.api import memcache
    ImportError: No module named 'google'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/shaurya/repos/api_test/eggs/google_api_python_client-1.6.4-py3.4.egg/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
        from oauth2client.contrib.locked_file import LockedFile
    ImportError: No module named 'oauth2client.contrib.locked_file'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/shaurya/repos/api_test/eggs/google_api_python_client-1.6.4-py3.4.egg/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
        from oauth2client.locked_file import LockedFile
    ImportError: No module named 'oauth2client.locked_file'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/shaurya/repos/api_test/eggs/google_api_python_client-1.6.4-py3.4.egg/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
        from . import file_cache
      File "/home/shaurya/repos/api_test/eggs/google_api_python_client-1.6.4-py3.4.egg/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
        'file_cache is unavailable when using oauth2client >= 4.0.0')
    ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
```

**Comment by henryrizzi** [comment]
I believe that this error trace is just a warning, and shouldn't affect anything being run. It just looks like something broke.
believe it's happening here:
https://github.com/google/google-api-python-client/blob/master/googleapiclient/discovery_cache/__init__.py

**Comment by bantini** [comment]
@XuryaX I am trying to replicate the issue. Can you share how your environment was set up, how you are using the library, etc. preferably with some code?

**Comment by bantini** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by jonasman** [comment]
I get the same with this libs:
google-api-python-client==1.6.5
google-auth==1.4.1
google-auth-httplib2==0.0.3
