### ISSUE TITLE
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

### ISSUE THREAD

**Issue by maheshgmv** [google/google-api-python-client#453]
I'm getting SSL error after oauth2 authentication

Warning (from warnings module):
  File "C:\Python27\lib\site-packages\oauth2client\_helpers.py", line 255
    warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
UserWarning: Cannot access analytics.dat: No such file or directory

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=907191080091-sn5in526069n94ubml97pcc5ckk1n67k.apps.googleusercontent.com&access_type=offline

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Traceback (most recent call last):
  File "C:\Users\mahevarma\Desktop\analytics\HelloAnalytics.py", line 113, in <module>
    main()
  File "C:\Users\mahevarma\Desktop\analytics\HelloAnalytics.py", line 107, in main
    service = get_service('analytics', 'v3', scope, 'client_secrets.json')
  File "C:\Users\mahevarma\Desktop\analytics\HelloAnalytics.py", line 43, in get_service
    credentials = tools.run_flow(flow, storage, flags)
  File "C:\Python27\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python27\lib\site-packages\oauth2client\tools.py", line 243, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "C:\Python27\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python27\lib\site-packages\oauth2client\client.py", line 2054, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "C:\Python27\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1319, in _conn_request
    conn.connect()
  File "C:\Python27\lib\site-packages\httplib2\__init__.py", line 1092, in connect
    raise SSLHandshakeError(e)
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
>>>

**Comment by bantini** [comment]
@maheshgmv Can you share the code that you are using for authentication?

**Comment by bantini** [comment]
Closing this issue because there was no response for over 7 days. Feel free to reopen this issue if the problem reappears.

**Comment by maheshgmv** [comment]
@bantini i'm using **hello_analytics_api_v3.py**  code for authentication.

**Comment by fivejjs** [comment]
I got the same error 

urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```python
n get_ADW_userlists
    adul_service = client.GetService('AdwordsUserListService', version=googleads
_version)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\googleads\a
dwords.py", line 454, in GetService
    **kwargs)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\suds\client
.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\suds\reader
.py", line 152, in open
    d = self.fn(url, self.options)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\suds\wsdl.p
y", line 136, in __init__
    d = reader.open(url)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\suds\reader
.py", line 79, in open
    d = self.download(url)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\suds\reader
.py", line 95, in download
    fp = self.options.transport.open(Request(url))
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\suds\transp
ort\http.py", line 62, in open
    return self.u2open(u2request)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\site-packages\suds\transp
ort\http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\urllib2.py", line 429, in
 open
    response = self._open(req, data)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\urllib2.py", line 447, in
 _open
    '_open', req)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\urllib2.py", line 407, in
 _call_chain
    result = func(*args)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\urllib2.py", line 1241, i
n https_open
    context=self._context)
  File "E:\APPS\RP_Jobs\Python\miniconda\envs\py27\lib\urllib2.py", line 1198, i
n do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:661)>
```

**Comment by bantini** [comment]
This is working fine for me. I would suggest the following:

1. Your system clock.
2. Your Python version. Older versions of 2.7 lack SNI support.
3. Your version of openssl, older versions can lack SNI support.
4. Your version of requests and certifi.
5. You can try installing requests[security] to see if it automatically fixes it.

**Comment by cubicova17** [comment]
Also getting the same mistake:
1. Clock is in sync
2-5 All were the same for the last months - but the lib stopped working today(approx. 4 hours ago).
Any other ideas how to trace the error?

**Comment by bantini** [comment]
@cubicova17 Which version of the library, and Python are you using?

**Comment by cubicova17** [comment]
- Python 2.7.13
- google-api-python-client==1.5.1
also I noticed that previously we used 
`pyOpenSSL==17.2.0`
but now some of our dependencies updated lib version to
`pyOpenSSL==17.3.0`
perhaps this can cause the problem.

**Comment by bantini** [comment]
@cubicova17 Can you try updating google-api-python-client to the latest version (1.6.4)?

**Comment by bantini** [comment]
Closing this issue, because it couldn't be replicated with the latest version.

**Comment by KathyShen** [comment]
Hi I'm facing the same issue. Got error message:

_urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:661)>_

Checked my python and lib versions, don;t think it's the version issue. Anyone can suggest what are the potential reason?
-- Python 2.7.13
-- google-api-python-client 1.6.5
-- pyOpenSSL 17.5.0

**Comment by dlrust** [comment]
@KathyShen I was also getting this error which started a few days ago from the googleapis.com URL

I'm on python 2.7.10

I upgraded the following packages to these versions in my project. I'd check to see if you have any of these listed in your requirements pointing at specific older versions

```
google-api-python-client==1.6.5
httplib2==0.10.3
oauth2client==4.1.2
PyOpenSSL==17.5.0
six==1.11.0
```

**Comment by oj8k** [comment]
Traceback (most recent call last):
  File "/usr/bin/gdfstool", line 125, in <module>
    main()
  File "/usr/bin/gdfstool", line 120, in main
    _handle_mountpoint(args)
  File "/usr/bin/gdfstool", line 72, in _handle_mountpoint
    option_string=option_string)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 863, in mount
    gdrivefs.gdtool.account_info.AccountInfo().get_data()
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/account_info.py", line 19, in get_data
    return gd.get_about_info()
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 56, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 190, in get_about_info
    client = self.__auth.get_client()
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 152, in get_client
    discoveryServiceUrl=discoveryUrl)
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1570, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1317, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1252, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1044, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
[root@vultr ~]# gdfstool mount /var/cache/gdfs.creds /mnt/gdrivefs
Traceback (most recent call last):
  File "/usr/bin/gdfstool", line 125, in <module>
    main()
  File "/usr/bin/gdfstool", line 120, in main
    _handle_mountpoint(args)
  File "/usr/bin/gdfstool", line 72, in _handle_mountpoint
    option_string=option_string)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 863, in mount
    gdrivefs.gdtool.account_info.AccountInfo().get_data()
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/account_info.py", line 19, in get_data
    return gd.get_about_info()
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 56, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 190, in get_about_info
    client = self.__auth.get_client()
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 152, in get_client
    discoveryServiceUrl=discoveryUrl)
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1570, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1317, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1252, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1044, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

**Comment by djfritz** [comment]
Seeing the same thing with the latest google appengine release, python 2.7.13

**Comment by zdavatz** [comment]
same problem here with Python version Python 2.7.12
```
Traceback (most recent call last):
  File "basic_upload_apks_service_account.py.1", line 86, in <module>
    main()
  File "basic_upload_apks_service_account.py.1", line 83, in main
    upload(args.package, args.service, args.apk, args.track)
  File "basic_upload_apks_service_account.py.1", line 42, in upload
    service = build('androidpublisher', 'v2', http=http_auth)
  File "/usr/lib64/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/googleapiclient/discovery.py", line 214, in build
    cache)
  File "/usr/lib64/python2.7/site-packages/googleapiclient/discovery.py", line 261, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/lib64/python2.7/site-packages/oauth2client/client.py", line 631, in new_request
    redirections, connection_type)
  File "/usr/lib64/python2.7/site-packages/httplib2-0.7.6-py2.7.egg/httplib2/__init__.py", line 1588, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib64/python2.7/site-packages/httplib2-0.7.6-py2.7.egg/httplib2/__init__.py", line 1336, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib64/python2.7/site-packages/httplib2-0.7.6-py2.7.egg/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/lib64/python2.7/site-packages/httplib2-0.7.6-py2.7.egg/httplib2/__init__.py", line 1037, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by mattwhisenhunt** [comment]
@zdavatz is your environment appengine too?

**Comment by zdavatz** [comment]
No. I am now using https://github.com/jeduan/playup to publish my APK from commandline. Works well.

**Comment by kaansoral** [comment]
This was happening to me too, I was using the sdk1.9.40 - updating my sdk to 1.9.70 fixed things

**Comment by graulito** [comment]
@kaansoral can you elaborate? You're talking about the gcloud app Python extensions right?
Not really sure how those extensions fit into all this

**Comment by kaansoral** [comment]
Oops, I was talking about the App Engine Linux Python SDK

**Comment by lucadealfaro** [comment]
Also seeing this.

**Comment by braunchris** [comment]
I am getting the same error with the following:
Python 2.7.15
google-api-python-client==1.7.9
httplib2==0.12.1
oauth2client==4.1.3
PyOpenSSL==18.0.0
six==1.12.0

**Comment by davepmarshall** [comment]
@braunchris Try upgrading your PyOpenSSL to 19.0.0 which supports OpenSSL 1.1.1

**Comment by busunkim96** [comment]
Hi @braunchris, if you are having the same issue please post to a new issue and reference this one. Repository maintainers are more likely to miss replies to closed issues.

Thanks!

**Comment by malavancs** [comment]
Update the httplib2 to latest version. It will solve the problem.

**Comment by LucasMMota** [comment]
I got the same problem and debugging the Google Lib I found out that the reason was that I was using an older version of `httplib2`(0.9.2). When I updated to the most recent (0.14.0) it worked.

If you already install the most recent, make sure that some lib is not installing an older version of `httplib2` inside its dependencies.

**Comment by KrisKusano** [comment]
I got a similar error on macOS Catalina using python 3.7.2 bundled with the OS. No such error using python 2.7.16 bundled with the OS. No error using `brew install python3` (3.7.6).

**Comment by speedplane** [comment]
I'm still getting this, here's my pip freeze:

```
cachetools==3.1.1
certifi==2019.11.28
chardet==3.0.4
crcmod==1.7
cssselect==0.9.1
enum34==1.1.9
et-xmlfile==1.0.1
futures==3.3.0
google-api-core==1.16.0
google-api-python-client==1.7.11
google-auth==1.11.2
google-auth-httplib2==0.0.3
google-cloud-core==1.3.0
google-cloud-datastore==1.10.0
google-cloud-logging==1.12.1
google-cloud-storage==1.19.0
google-cloud-tasks==1.2.1
google-python-cloud-debugger==2.14
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
grpc-google-iam-v1==0.12.3
grpcio==1.27.2
httplib2==0.17.0
idna==2.9
jdcal==1.4.1
Jinja2==2.6
lxml==2.3
mercurial==3.7.3
netaddr==0.7.19
nltk==3.2
numpy==1.11.0
openpyxl==2.6.0
Pillow==3.1.1
protobuf==3.11.3
psutil==5.4.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycrypto==2.6
pytz==2019.3
PyYAML==5.3
requests==2.23.0
rsa==4.0
selenium==3.5.0
six==1.14.0
stem==1.1.0
uritemplate==3.0.1
urllib3==1.25.8
virtualenv==16.0.0
xlrd==1.2.0
```

**Comment by sdupere-git** [comment]
Same issue here

**Comment by kmeeraj** [comment]
I have followed this step and it worked for me (look for my comments) :
https://stackoverflow.com/questions/45927259/google-cloud-python-sdk-installation-error-ssl-certification-error/50524168#50524168

**Comment by mrodrig** [comment]
In my case, I needed to add the certs to the `certifi` package and then my use case started working:
```
cat my_cert_file.crt >> env/lib/python3.9/site-packages/httplib2/cacerts.txt
cat my_cert_file.crt >> env/lib/python3.9/site-packages/pip/_vendor/certifi/cacert.pem
cat my_cert_file.crt >> env/lib/python3.9/site-packages/certifi/cacert.pem
```

You mileage may vary, but hopefully this helps someone out.

**Comment by AshuT930** [comment]
I was using google drive API in my python code and am also facing the same issue, 
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)`
I tried most of the steps mentioned here but nothing works.

**Comment by leiforion** [comment]
For those who are still running into this issue on OSX, as it seems to still crop up from time to time, I was able to solve it by installing the most recent version of the gcloud SDK. OSX python has become pretty convoluted so many of the older solutions here were not quite accurate or seemed to be missing some key info. Note that when you install the sdk you will likely be prompted to change your python version. That said, the installation of the sdk seems to include some of the necessary certificates etc. to get things working again. It's also possible that just upgrading python 3.11 would have helped but worth a try if all else fails.
