### ISSUE TITLE
SyntaxError in "django-sample" when tried to run the sample

### ISSUE THREAD

**Issue by ecarradal** [google/google-api-python-client#462]
Hello :D 
I have this issue when I tried to run the sample
```
(venv) Eduardos-iMac:django_sample ecarradal$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from django.core.management import execute_manager
  File "/Users/ecarradal/Documents/documents/decidata/google-api-python-client/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 52
    except ImportError,e:
                      ^
SyntaxError: invalid syntax
```

**Comment by bantini** [comment]
@ecarradal I am assuming you are using Python 3.6? Which version of Django are you using? Also, is it a Mac/PC/Linux machine?

**Comment by bantini** [comment]
Closing this because there was no response for 7 days, so I am assuming the issue has been resolved. Feel free to reopen this if the problem persists.
