### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'syntax' in http_pb2.py

### ISSUE THREAD

**Issue by alexandermichels** [google/google-api-python-client#508]
Hello, I'm trying to use Google Cloud's Text-To-Speech and I am getting this traceback when I try importing texttospeech from google.cloud. I installed the SDK using [Google's Quickstart for Debian/Ubuntu and Python](https://cloud.google.com/sdk/docs/) and the Python libraries using pip. I've tried upgrading using pip and still get this error, I've used the import in different Python scripts and get the same error, and I Googled around saw the problem might be protobuf so I uninstalled/reinstalled/upgraded and still getting the error. Any ideas?

>>> runfile('/home/alex/Documents/GitHubRepositories/TitanRadio/WeatherWaves/WeatherReporter.py', wdir='/home/alex/Documents/GitHubRepositories/TitanRadio/WeatherWaves')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)
  File "/home/alex/Documents/GitHubRepositories/TitanRadio/WeatherWaves/WeatherReporter.py", line 5, in <module>
    from google.cloud import texttospeech
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/texttospeech.py", line 17, in <module>
    from google.cloud.texttospeech_v1beta1 import TextToSpeechClient
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/texttospeech_v1beta1/__init__.py", line 17, in <module>
    from google.cloud.texttospeech_v1beta1 import types
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/texttospeech_v1beta1/types.py", line 20, in <module>
    from google.api import http_pb2
  File "/usr/local/lib/python2.7/dist-packages/google/api/http_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x15google/api/http.proto\x12\ngoogle.api\"+\n\x04Http\x12#\n\x05rules\x18\x01 \x03(\x0b\x32\x14.google.api.HttpRule\"\xea\x01\n\x08HttpRule\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\r\n\x03get\x18\x02 \x01(\tH\x00\x12\r\n\x03put\x18\x03 \x01(\tH\x00\x12\x0e\n\x04post\x18\x04 \x01(\tH\x00\x12\x10\n\x06\x64\x65lete\x18\x05 \x01(\tH\x00\x12\x0f\n\x05patch\x18\x06 \x01(\tH\x00\x12/\n\x06\x63ustom\x18\x08 \x01(\x0b\x32\x1d.google.api.CustomHttpPatternH\x00\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x12\x31\n\x13\x61\x64\x64itional_bindings\x18\x0b \x03(\x0b\x32\x14.google.api.HttpRuleB\t\n\x07pattern\"/\n\x11\x43ustomHttpPattern\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\tB\'\n\x0e\x63om.google.apiB\tHttpProtoP\x01\xf8\x01\x01\xa2\x02\x04GAPIb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by mcdonc** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-python#5548
