### ISSUE TITLE
Recently released package 1.7.0 is bad? "RuntimeError: Previous version of google-api-python-client detected"

### ISSUE THREAD

**Issue by jtattermusch** [google/google-api-python-client#516]
We started getting an error  right after 1.7.0 was pushed to pip:

```
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 49, in <module>
    from python_utils.upload_test_results import upload_results_to_bq
  File "/Volumes/BuildData/tmpfs/src/github/grpc/tools/run_tests/python_utils/upload_test_results.py", line 29, in <module>
    import big_query_utils
  File "/Volumes/BuildData/tmpfs/src/github/grpc/tools/gcp/utils/big_query_utils.py", line 21, in <module>
    from apiclient import discovery
  File "/Users/kbuilder/Library/Python/2.7/lib/python/site-packages/apiclient/__init__.py", line 11, in <module>
    'Previous version of google-api-python-client detected; due to a '
RuntimeError: Previous version of google-api-python-client detected; due to a packaging issue, we cannot perform an in-place upgrade. To repair, remove and reinstall this package, along with oauth2client and uritemplate. One can do this with pip via
  pip install -I google-api-python-client
```

in out script this happens after we pip install the freshest version of  google-api-python-client.

see  https://github.com/grpc/grpc/issues/15600

Seems that something is bad with the package, can you fix or unpublish?

**Comment by theacodes** [comment]
It's weird that your scripts are using the source dist instead of the wheel, which wouldn't hit this codepath at all. 

Releasing a version to remove this check, as it's no longer necessary at all.

**Comment by jtattermusch** [comment]
Looks like if we remove the `==1.6.7` pin, things are still broken with 1.7.1 package.

Install 1.7.1:
```
++ pip install google-api-python-client --user python
Collecting google-api-python-client
  Downloading https://files.pythonhosted.org/packages/77/24/6a493cff23e60d882598e92b03d9f2c3c77299a9578b4411636616c039f4/google_api_python_client-1.7.1-py2.py3-none-any.whl (55kB)
Requirement already satisfied: python in /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
Requirement already satisfied: six<2dev,>=1.6.1 in /usr/local/lib/python2.7/site-packages (from google-api-python-client)
Collecting google-auth>=1.4.1 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/53/06/6e6d5bfa4d23ee40efd772d6b681a7afecd859a9176e564b8c329382370f/google_auth-1.5.0-py2.py3-none-any.whl (65kB)
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/f6/25/66a49231b44409d7f07cfcf2506a8b070ce3c99fc47cc256bea833f24791/uritemplate-3.0.0-py2-none-any.whl
Requirement already satisfied: httplib2<1dev,>=0.9.2 in /usr/local/lib/python2.7/site-packages (from google-api-python-client)
Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.4.1->google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/e9/51/bcd96bf6231d4b2cc5e023c511bee86637ba375c44a6f9d1b4b7ad1ce4b9/pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth>=1.4.1->google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl (46kB)
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/a0/70/2c27740f08e477499ce19eefe05dbcae6f19fdc49e9e82ce4768be0643b9/pyasn1-0.4.3-py2.py3-none-any.whl (72kB)
Installing collected packages: pyasn1, pyasn1-modules, cachetools, rsa, google-auth, uritemplate, google-auth-httplib2, google-api-python-client
Successfully installed cachetools-2.1.0 google-api-python-client-1.7.1 google-auth-1.5.0 google-auth-httplib2-0.0.3 pyasn1-0.4.3 pyasn1-modules-0.2.1 rsa-3.4.2 uritemplate-3.0.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

And the error:
```
RuntimeError: Previous version of google-api-python-client detected; due to a packaging issue, we cannot perform an in-place upgrade. To repair, remove and reinstall this package, along with oauth2client and uritemplate. One can do this with pip via
  pip install -I google-api-python-client
2018-06-04 02:35:40,745 FAILED: run_tests_objc_macos_dbg_native [ret=1, pid=22864, time=13.0sec]
2018-06-04 02:35:40,771 FAILED: Some run_tests.py instance have failed.
```

https://source.cloud.google.com/results/invocations/8ea5e422-bc99-46ab-88e3-a2c066e688b7/targets
