### ISSUE TITLE
Google Cloud Storage Not Uploading Files on Local Development Server

### ISSUE THREAD

**Issue by migdall** [google/google-api-python-client#528]
When trying to test uploading of images on the local development server I am running into this issue.

So far this is not affecting the versions of the app deployed online, just the local environment.

This uploading images code was working fine and then now its not working.

I tried gcloud init and gcloud auth but the error persists.

```
INFO     2018-05-05 02:07:42,905 client.py:755] Refreshing access_token
INFO     2018-05-05 02:07:43,173 client.py:777] Failed to retrieve access token: {
  "error" : "invalid_client",
  "error_description" : "The OAuth client was not found."
}
ERROR    2018-05-05 02:07:43,173 api_server.py:373] Exception while handling app_identity_service.GetAccessToken()
Traceback (most recent call last):
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 341, in _handle_POST
    api_response = _execute_request(request).Encode()
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 162, in _execute_request
    make_request()
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 157, in make_request
    request_id)
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub.py", line 151, in MakeSyncCall
    method(request, response)
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/google/appengine/api/app_identity/app_identity_defaultcredentialsbased_stub.py", line 197, in _Dynamic_GetAccessToken
    token = credentials.get_access_token()
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/lib/oauth2client_devserver/oauth2client/client.py", line 642, in get_access_token
    self.refresh(http)
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/lib/oauth2client_devserver/oauth2client/client.py", line 559, in refresh
    self._refresh(http.request)
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/lib/oauth2client_devserver/oauth2client/client.py", line 728, in _refresh
    self._do_refresh_request(http_request)
  File "/Users/jesusnoland/google-cloud-sdk/platform/google_appengine/lib/oauth2client_devserver/oauth2client/client.py", line 790, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
AccessTokenRefreshError: invalid_client: The OAuth client was not found.

WARNING  2018-05-05 02:07:43,178 tasklets.py:468] suspended generator _make_token_async(rest_api.py:103) raised RuntimeError(AccessTokenRefreshError(u'invalid_client: The OAuth client was not found.',))
WARNING  2018-05-05 02:07:43,179 tasklets.py:468] suspended generator get_token_async(rest_api.py:214) raised RuntimeError(AccessTokenRefreshError(u'invalid_client: The OAuth client was not found.',))
WARNING  2018-05-05 02:07:43,179 tasklets.py:468] suspended generator urlfetch_async(rest_api.py:247) raised RuntimeError(AccessTokenRefreshError(u'invalid_client: The OAuth client was not found.',))
WARNING  2018-05-05 02:07:43,179 tasklets.py:468] suspended generator run(api_utils.py:164) raised RuntimeError(AccessTokenRefreshError(u'invalid_client: The OAuth client was not found.',))
WARNING  2018-05-05 02:07:43,180 tasklets.py:468] suspended generator do_request_async(rest_api.py:190) raised RuntimeError(AccessTokenRefreshError(u'invalid_client: The OAuth client was not found.',))
WARNING  2018-05-05 02:07:43,180 tasklets.py:468] suspended generator do_request_async(storage_api.py:128) raised RuntimeError(AccessTokenRefreshError(u'invalid_client: The OAuth client was not found.',))
CRITICAL 2018-05-05 02:07:43,180 models.py:761] RuntimeError image was not uploaded to google: (AccessTokenRefreshError(u'invalid_client: The OAuth client was not found.',))
```

```
import os
import cloudstorage as gcs

from google.appengine.api import app_identity


def get_default_file_bucket_name():
    """ Get the default Google Cloud Storage bucket for the mylitpen app """
    bucket_name = os.environ.get('testapp.appspot.com', app_identity.get_default_gcs_bucket_name())
    return bucket_name


def save_image_file(image, idea_id):
    """ Save the image to Google Cloud Storage """
    write_retry_params = gcs.RetryParams(backoff_factor=1.1)
    bucket_name = get_default_file_bucket_name()
    gcs_file = gcs.open('/%s/images/%s.jpg' % (bucket_name, idea_id),
                        'w',
                        content_type='image/jpeg',
                        retry_params=write_retry_params)
    gcs_file.write(image)
    gcs_file.close()
    return gcs_file
```

I am uploading the images to Google Cloud Storage.

**Comment by mcdonc** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-python#5662

**Comment by mcdonc** [comment]
This bug was slightly misfiled.  I used a Github "issue mover" to put this issue into the correct place, which created https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5662 .
