### ISSUE TITLE
_retry_request does not catch ServerNotFoundError

### ISSUE THREAD

**Issue by bashir2** [google/google-api-python-client#529]
It seems to me that `http._retry_request` does not catch `ServerNotFoundError` when it calls `http.request` [here](https://github.com/google/google-api-python-client/blob/b0b1c1d4a68ae0a40d64c2570425a355362803ba/googleapiclient/http.py#L162). IIUC, this exception might be raised from httplib2 [here](https://github.com/jcgregorio/httplib2/blob/010b4e399c04a199e7ca25995286f3db0337500d/python2/httplib2/__init__.py#L1278) and I wonder why it is not being caught for a retry.

**Comment by theacodes** [comment]
This is generally a terminal error, as DNS lookup failures tend to be pretty fatal. Where are you seeing this and how does retrying help?

**Comment by bashir2** [comment]
Hmm, can't a temporary network connection issue cause DNS resolution failures?

The actual error I was debugging is coming from a VM on GCP trying to reach out to some Google Cloud APIs so this is entirely internal to GCP (although reported by an external user). I have copied the full traceback below:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/gcp_variant_transforms/src/gcp_variant_transforms/vcf_to_bq.py", line 261, in <module>
    run()
  File "/opt/gcp_variant_transforms/src/gcp_variant_transforms/vcf_to_bq.py", line 196, in run
    runner.wait_until_done()
  File "gcp_variant_transforms/libs/annotation/vep/vep_runner.py", line 256, in wait_until_done
    if not self._is_done(op)]
  File "gcp_variant_transforms/libs/annotation/vep/vep_runner.py", line 267, in _is_done
    is_done = request.execute(num_retries=_NUMBER_OF_API_CALL_RETRIES)['done']
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/googleapiclient/http.py", line 835, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/googleapiclient/http.py", line 162, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at genomics.googleapis.com
```

**Comment by bashir2** [comment]
That I don't know :-) but this was a long running job (>20 hours) and I suppose we should account for possible network issues even for GCP instances.

Re. your concern, if we retry and the issue is actually permanent, this will eventually fail, correct? I mean we won't mask any permanent issue.

**Comment by theacodes** [comment]
I mean, sure, let's do it. Send a PR?

**Comment by bashir2** [comment]
PR #532 sent; @theacodes can you please take a look?

**Comment by bashir2** [comment]
@theacodes thanks for merging this. Do you have any idea of when the next release will be done such that I can pick up this fix in downstream projects?
