### ISSUE TITLE
Problems with mediaItems().search() for photos api

### ISSUE THREAD

**Issue by jparris** [google/google-api-python-client#549]
Hi There,

I'm trying to list a google photo library using the [api](https://developers.google.com/photos/library/guides/list#listing-library-contents) in python.

# Code
get_authenticated_service is from [chunked_transfer.py](https://github.com/GoogleCloudPlatform/storage-file-transfer-json-python/blob/master/chunked_transfer.py)
```
import httplib2
import os

from apiclient.discovery import build as discovery_build
from apiclient.errors import HttpError
from apiclient.http import MediaFileUpload
from apiclient.http import MediaIoBaseDownload
from json import dumps as json_dumps
from oauth2client.client import flow_from_clientsecrets
from oauth2client.file import Storage as CredentialStorage
from oauth2client.tools import run_flow as run_oauth2

# CLIENT_SECRETS_FILE, name of a file containing the OAuth 2.0 information for
# this application, including client_id and client_secret. You can acquire an
# ID/secret pair from the API Access tab on the Google APIs Console
#   <http://code.google.com/apis/console#access>
# For more information about using OAuth2 to access Google APIs, please visit:
#   <https://developers.google.com/accounts/docs/OAuth2>
CLIENT_SECRETS_FILE = 'client_secrets.json'

# File where we will store authentication credentials after acquiring them.
CREDENTIALS_FILE = 'credentials.json'

# Setup the Photo v1 API
SCOPES = 'https://www.googleapis.com/auth/photoslibrary.readonly'

MISSING_CLIENT_SECRETS_MESSAGE = """
WARNING: Please configure OAuth 2.0

To make this sample run you will need to populate the client_secrets.json file
found at:

   %s

with information from the APIs Console
<https://code.google.com/apis/console#access>.

""" % os.path.abspath(os.path.join(os.path.dirname(__file__),
                                   CLIENT_SECRETS_FILE))


def get_authenticated_service():
    flow = flow_from_clientsecrets(CLIENT_SECRETS_FILE, scope=SCOPES, message=MISSING_CLIENT_SECRETS_MESSAGE)

    credential_storage = CredentialStorage(CREDENTIALS_FILE)
    credentials = credential_storage.get()
    if credentials is None or credentials.invalid:
        credentials = run_oauth2(flow, credential_storage)

    print "Constructing Google Cloud Storage service."
    http = credentials.authorize(httplib2.Http())
    return discovery_build('photoslibrary', 'v1', http=http)

if __name__ == '__main__':
    service = get_authenticated_service()
    print dir(service.mediaItems().search(body="{\"pageSize\":\"100\"}").execute())
```
 
# Error
```
$ python foo.py 
Constructing Google Cloud Storage service.
Traceback (most recent call last):
  File "quickstart.py", line 65, in <module>
    print dir(service.mediaItems().search(body="{\"pageSize\":\"100\"}").execute())
  File "/home/parrisj/src/kallitype/scripts/google-env/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/parrisj/src/kallitype/scripts/google-env/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://photoslibrary.googleapis.com/v1/mediaItems:search?alt=json returned "Invalid JSON payload received. Unknown name "": Root element must be a message.">
```

# Version info
```
$ python --version
Python 2.7.14
$ pip show google-api-python-client
Name: google-api-python-client
Version: 1.7.4
Summary: Google API Client Library for Python
Home-page: http://github.com/google/google-api-python-client/
Author: Google Inc.
Author-email: UNKNOWN
License: Apache 2.0
Location: /home/parrisj/src/kallitype/scripts/google-env/lib/python2.7/site-packages
Requires: six, google-auth, uritemplate, httplib2, google-auth-httplib2
Required-by: 
```

**Comment by mcdonc** [comment]
@jparris you don't need to pass JSON as the body.  Instead:

```
print (service.mediaItems().search(body={"pageSize":"100"}).execute())
```

**Comment by jparris** [comment]
@mcdonc this works for me. Thanks for the prompt response.

-Jon
