### ISSUE TITLE
Uploading a huge file overflow error

### ISSUE THREAD

**Issue by sagiegurari** [google/google-api-python-client#74]
I get an overflowerror when uploading a very large file.
full stack (i'm using raspberry pi which is 32 bit OS and the file is over 4 gig and python 2.7):

```
Traceback (most recent call last):
  File "./drive_upload.py", line 33, in <module>
    backupFile.Upload()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/files.py", line 225, in Upload
    self._FilesInsert(param=param)
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 54, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pydrive/files.py", line 241, in _FilesInsert
    metadata = self.auth.service.files().insert(**param).execute()
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 750, in method
    payload = media_upload.getbytes(0, media_upload.size())
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 357, in getbytes
    return self._fd.read(length)
OverflowError: Python int too large to convert to C long
```

**Comment by sagiegurari** [comment]
also, why should it try to read the entire file into memory? makes no sense for huge files.
should stream the file instead over http.

**Comment by Lyrrad** [comment]
Streaming is supported by the underlying classes.  However, PyDrive doesn't appear to support it.  Take a look at the sample Python code at https://developers.google.com/drive/v2/reference/files/insert

**Comment by sagiegurari** [comment]
thanks, I'll check it out.

**Comment by sagiegurari** [comment]
works great with a file size of 4gig, so the issue is definitely in pydrive.
thanks a lot.
