### ISSUE TITLE
BigQuery Client Api Library - Load operations raises Not Found Error when the table already exists in the dataset

### ISSUE THREAD

**Issue by WesleyBatista** [google/google-api-python-client#85]
For security reasons I can't publish specific additional informations, but I will try to detail as much as I can.

I have these tables on 'Sandbox' dataset:
- Sandbox.test4
- Sandbox.test5

```
a = bqLoader.loadAssync("/home/wesley/k/codes_return20150320.csv", "Sandbox", "test3", "/home/wesley/Desktop/loadFileTestSchema.json", )
print a
b = bqLoader.loadAssync("/home/wesley/k/codes_return20150321.csv", "Sandbox", "test4", "/home/wesley/Desktop/loadFileTestSchema.json", )
print b
c = bqLoader.loadAssync("/home/wesley/k/codes_return20150322.csv", "Sandbox", "test5", "/home/wesley/Desktop/loadFileTestSchema.json", )
print c
```

the above code's output:

```
<googleapiclient.http.MediaFileUpload object at 0x7f9580e94850>
job_xxxxxxxxC2WY6SlEFTrtaxxxxx

Traceback (most recent call last):
  File "/home/wesley/github/BI/helpers/BigQuery/BigQueryLoad.py", line 130, in <module>
    b = bqLoader.loadAssync("/home/wesley/k/codes_return20150321.csv", "Sandbox", "test4", "/home/wesley/Desktop/loadFileTestSchema.json", )
  File "/home/wesley/github/BI/helpers/BigQuery/BigQueryLoad.py", line 122, in loadAssync
    jobId = self._jobsInsert(jobData, upload)["jobReference"]["jobId"]
  File "/home/wesley/github/BI/helpers/BigQuery/BaseClass.py", line 107, in _jobsInsert
    raise e
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/upload/bigquery/v2/projects/PROJECT_ID/jobs?uploadType=multipart&alt=json returned "Not Found: Job PROJECT_ID:JOB_ID">
```

**Comment by WesleyBatista** [comment]
Just to clarify a little bit:
my loadAssync method can receive 'replace' parameter which so that calls another method which replaces the "writeDisposition" default value from the config json with "WRITE_TRUNCATE".

I just think there should be a better way to handle this type of error than 404

**Comment by mcdonc** [comment]
Triaging:

I'm afraid I can't make sense of this without seeing the implementation of loadAssync.  Really can't do much with this without.

**Comment by mcdonc** [comment]
Another theory is a typo in the project id...

```
The query string parms ('uploadType=multipart&alt=json') suggest that it is the POST for 'jobs.insert' which is raising the 404, which makes a typo in the project ID the favorite
```

**Comment by JustinBeckwith** [comment]
Greetings!  For BigQuery, we recommend using this library instead:
https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery

Hope this helps!
