### ISSUE TITLE
Python3 - tools.ClientRedirectHandler.do_GET needs to write bytes, not strings

### ISSUE THREAD

**Issue by AcXesZ** [google/google-api-python-client#91]
When Authentication Flow completes, an attempt to alert the user in the browser is made.  Using google-api-python-client-py3, an exception is thrown:

Traceback (most recent call last):
  File "C:\Python33\Lib\socketserver.py", line 306, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python33\Lib\socketserver.py", line 332, in process_request
    self.finish_request(request, client_address)
  File "C:\Python33\Lib\socketserver.py", line 345, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python33\Lib\socketserver.py", line 666, in __init__
    self.handle()
  File "C:\Python33\Lib\http\server.py", line 400, in handle
    self.handle_one_request()
  File "C:\Python33\Lib\http\server.py", line 388, in handle_one_request
    method()
  File "C:\python_projects\pdns\lib\site-packages\oauth2client\tools.py", line 100, in do_GET
    s.wfile.write("<html><head><title>Authentication Status</title></head>")
  File "C:\Python33\Lib\socket.py", line 317, in write
    return self._sock.send(b)
TypeError: 'str' does not support the buffer interface

Fixed by changing the following lines in tools.ClientRedirectHandler.do_GET():
`s.wfile.write(bytes("<html><head><title>Authentication Status</title></head>", "UTF-8"))
s.wfile.write(bytes("<body><p>The authentication flow has completed.</p>", "UTF-8"))
s.wfile.write(bytes("</body></html>", "UTF-8"))`

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the report! Since you have a notion of how it should be fixed, what would you think about creating a pull request?

**Comment by AcXesZ** [comment]
My apologies.  The problem is in the oauth2client module.
